### ISSUE TITLE
Compatibility issue with Enhanced Steam addon

### ISSUE THREAD

**Issue by lboklin** [tryton-vanmeer/ProtonDB-for-Steam#14]
The rating disappears from the store page when using [Enhanced Steam](https://www.enhancedsteam.com/)
Firefox 65.0 
SPCR-for-Steam 1.3.1
Enhanced Steam 10.0

**Comment by C-O-S** [comment]
Just a suggestion:
You may want to switch from Enhanced Steam, since it's end of life per the blog: https://www.enhancedsteam.com/blog/

... and instead move over to Augmented Steam, https://es.isthereanydeal.com/ - since it's under active development.
