### ISSUE TITLE
Ratings are no longer being displayed on Steam wishlists

### ISSUE THREAD

**Issue by flori4nk** [tryton-vanmeer/ProtonDB-for-Steam#19]
## Expected Behaviour:
* Ratings should be displayed on wishlists

## Actual Behaviour:
* Ratings aren't being displayed

## Steps to Reproduce:
1. Open any wishlist

## Details
Browser:
* [x] Firefox
* [ ] Chrome

Browser Version: **69.0.1**

Addon Version: **1.5.1**, downloaded from addons.mozilla.org

**Comment by tryton-vanmeer** [comment]
Showing ratings in the wishlist by default is off and can be enabled in the addons preferences.

**Comment by tryton-vanmeer** [comment]
Now that I've thought about it, I want to do some cleanup of the code. I'll likely remove showing ratings in the wishlist for now.
