### ISSUE TITLE
Green "NATIVE" ProtonDB rating for native games

### ISSUE THREAD

**Issue by fallenguru** [tryton-vanmeer/ProtonDB-for-Steam#23]
Currently, for native games, the ProtonDB rating info is just missing. I have to admit I find that confusing. It always takes me a while to realise that it must be native, scroll down and check. Since ProtonDB itself does list native games, as "NATIVE" on a green background, I'd suggest that the extension do that as well.

**Comment by raneon** [comment]
It would be nice that nevertheless the ProtonDB rating would be shown always. There are many Proton ratings even for native Linux games and now I have to look up the rating now manually if I decide to try out the Proton version. Maybe show NATIVE plus the ProtonDB rating?

**Comment by flori4nk** [comment]
I think a "View on ProtonDB" button should be added instead of showing 
the NATIVE rating.

**Comment by flori4nk** [comment]
A green rating badge is unnecessary as we already have the SteamOS symbol on store pages, besides the ProtonDB API returns the rating for the non-native builds running under Proton, why don't we utilize that?

**Comment by fallenguru** [comment]
> There are many Proton ratings even for native Linux games [...]. Maybe show NATIVE plus the ProtonDB rating?

@raneon: I agree, that would be best.

> I think a "View on ProtonDB" button should be added instead of showing the NATIVE rating.

@flori4nk: What purpose would that serve? Clicking the Proton badge (including the proposed NATIVE one) already links to ProtonDB in addition to providing information at a glance. Besides, Augmented Steam already does that.

> A green rating badge is unnecessary as we already have the SteamOS symbol on store pages.

@flori4nk: One, the SteamOS symbol isn't reliably present in my experience, neither are Linux system requirements. Two, they are way down on the page, in different locations. I'd like to be able to gauge whether I can play a game in Linux *at a single glance at a fixed place*.

Say there's a sale on, I'll open everything that looks interesting in a new tab, could be tens of them, then go through them at high speed to filter out everything that'll run poorly or not at all in a first pass. I'd rather not have to scroll or click anything for that. If the badge is missing that throws off my pattern recognition.
