### ISSUE TITLE
ENHANCEMENT: Star Whitelisted Games

### ISSUE THREAD

**Issue by jcc10** [tryton-vanmeer/ProtonDB-for-Steam#24]
Have a star (Or other symbol) to show when a game is whitelisted by steam.

**Comment by jcc10** [comment]
> So, we have an appid (891390). Now we just need to find out how to read the config.

May not even need to do that since ProtonDB shows whitelisted games. Depending on how this gets it's data, it may already be loaded, just not displayed.

**Comment by tryton-vanmeer** [comment]
As a solution for now, I have created a script to scrape SteamDB and generate a list of whitelisted games. So while updating the list is manual, the process is automated.

This also adds the benefit of not needing to query the whitelist for every page load.
