### ISSUE TITLE
Logs browser out of steamcommunity.com

### ISSUE THREAD

**Issue by codingthat** [tryton-vanmeer/ProtonDB-for-Steam#27]
## Expected Behaviour:
* Stay logged in (especially with "remember this computer" checked when logging in)

## Actual Behaviour:
* Doesn't

## Steps to Reproduce:
1. Log in
2. Close Firefox
3. Open Firefox
4. Navigate to steamcommunity.com
5. It's no longer logged in
6. Disable ProtonDB-for-Steam extension
7. Repeat 1-4
8. This time it has stayed logged in

I also tried deleting my cookies.sqllite (and bak) files (while FF was closed) but the result was the same.  It would not stay logged in.

## Details
Browser:
* [x] Firefox
* [ ] Chrome

Browser Version: 78.0.2 (64-bit) on Linux Mint 19.3

Addon Version: 1.7.0

**Comment by flori4nk** [comment]
ProtonDB-for-Steam doesn't touch cookies at all. Probably an issue on 
your side.

**Comment by flori4nk** [comment]
In fact, it doesn't send any requests to Steam servers by itself. It 
only fetches the rating from the protondb API and inserts an element 
into the document.

**Comment by codingthat** [comment]
Weird.  I definitely had 4 failures in a row, then removed the extension—no other changes—then had success.  Well, thank you for the insight, anyway.

**Comment by codingthat** [comment]
Just to confirm, you're right, re-enabling the extension, it still works between FF opens.  Extensions changes must trigger something related to this, I guess?  Insert big shrug here.
