### ISSUE TITLE
Add instructions for Chrome

### ISSUE THREAD

**Issue by multimeric** [tryton-vanmeer/ProtonDB-for-Steam#32]
Although they removed this from the Chrome store, I had no issues actually installing it from the releases page, using the following steps:

* Download the source code of the latest release from [the releases page](https://github.com/tryton-vanmeer/ProtonDB-for-Steam/releases)
* Untar/zip the archive
* Browse to <chrome://extensions/> in chrome
* Click "Load unpacked" at the top left
* Browse to `/path/to/ProtonDB-for-Steam-X.X.X/src`, and click okay
* Ignore the warning about `Unrecognized manifest key 'applications'`

It might be helpful to add this to the readme for people using Chrome.

**Comment by tryton-vanmeer** [comment]
I was providing a CRX file, but I kinda got lazy about that. I'll add these instructions to the README. 

I should also add a note about possible breaking changes, and for people to make issues if Chrome specific issues pop-up.

**Comment by multimeric** [comment]
Cheers, that sounds good!

**Comment by Julmik647** [comment]
You can create file like Chromium-instructions.md and create button next to Firefox button that redirects to this. You can use something similar to [LibRedirect Chromium button](https://libredirect.github.io/download.html) or ask for using exact same button.
