### ISSUE TITLE
Addon for Chromium

### ISSUE THREAD

**Issue by gituser823** [tryton-vanmeer/ProtonDB-for-Steam#33]
Hello,

this is not a bugrequest, but a feature request.
Could you make the addon also available for chromium based browsers?
That would be awesome, thanks!

**Comment by tryton-vanmeer** [comment]
I had ProtonDB-for-Steam on the Chrome web store, but Google took it down without reason.

ProtonDB-for-Steam works in Chromium based browsers and I recently added docs with the detailed steps for [installing the extension manually](https://github.com/tryton-vanmeer/ProtonDB-for-Steam/blob/master/docs/Install-Manually.md)

**Comment by gituser823** [comment]
Hi,

I just tired that, but I get the error Manifest-file is missing or unreadable.
I am using Brave Browser.
Is there any way to fix this?
Thanks.

**Comment by tryton-vanmeer** [comment]
When i get a chance today, I'll test it out and Brave. 

If I figure out the issue, ill make sure to update the docs and reply here.

**Comment by tryton-vanmeer** [comment]
Sorry for the delay.

After testing I realized I could be more specific in the instructions. After extracting the release zip, you just need to make sure to select the `src` directory when loading the unpacked extension.
