### ISSUE TITLE
Possibility to remove underline

### ISSUE THREAD

**Issue by Tiagoquix** [tryton-vanmeer/ProtonDB-for-Steam#46]
Hi there.

With the new update to adapt to the new wishlist format, ProtonDB links appear underlined to me. Previously, they didn't. And no, I don't use any browser settings or style extensions to add underlines.

![image](https://github.com/user-attachments/assets/3f5751b5-4b45-4875-84dc-0812c3f67374)

Could you make it so it doesn't add underline by default or make an option to toggle/disable it?

Thanks in advance.

**Comment by tryton-vanmeer** [comment]
Totally overlooked it, thanks for the report.

Pushed a new release to fix this.
